### ISSUE TITLE
finger pointing emojis replacing (almost) all bullet points after 0.0.35 update

### ISSUE THREAD

**Issue by paraversal** [fnumatic/obsidian-plugin-dynamic-toc#4]
Hi! so, after the newest update, there is a weird assortment of "👉" emojis spread throughout all documents. Specifically, almost all bullet points have been replaced by it, and also some other characters (like the last character before closing italic text and inline code delimiters. 
These are purely visual - disabling the plugin makes the emoji disappear.

edit:
- this happens on my macos machine, and on my iPhone as well.
- happens on a minimal config with an empty vault and just BRAT and TOC

**Comment by fnumatic** [comment]
yes sorry, I already noticed that fxckxp
will fix this asap

**Comment by paraversal** [comment]
Awesome. Thanks for maintaining this plugin!

edit: oops, accidentally closed the issue. But I guess it's getting fixed soon anyway
